### ISSUE TITLE
currently the connection to rabbitmq is not checked for errors

### ISSUE THREAD

**Issue by cglewis** [Lab41/PoseidonML#18]
inside of `AbnormalDetector/eval_classifier.py` the connection to rabbit needs to be minimally put in a try/except, but ideally it would have an environment variable to send to rabbit or log to stdout (in case a connection to rabbitmq isn't available)

**Comment by krb1997** [comment]
I have use this library before and can help. Just for clarification, what would you like from the environment variable?

**Comment by cglewis** [comment]
something like `SKIP_RABBIT=true` and if the variable doesn't exist then assume it should use rabbit.

**Comment by krb1997** [comment]
@cglewis Awesome. Ill be happy to work on this although ill be starting tomorrow if thats good with you?

**Comment by cglewis** [comment]
sounds good!

**Comment by krb1997** [comment]
@cglewis I have submitted a pull request for your viewing pleasure!

**Comment by krb1997** [comment]
@cglewis No problem!
