### ISSUE TITLE
Need sample "label_assignments.json" file

### ISSUE THREAD

**Issue by gregs5** [Lab41/PoseidonML#42]
Need sample label_assignments.json file in the pcap training directory. (There is none - it's currently expected, but missing).  Ideally, also include something like a README file that guides the user on the syntax of the file, and the fact that keys in the file are used in parsing the pcaps filenames when training. 

Perhaps a label_assignments.json.readme that says something like:

-----
The label_assignments.json file must be configured to include the proper prefixes for the packet captures (pcaps) that you would like to train from.  The key is the filename prefix (which expects a dash afterwards), and the value is the label you would like to use.  For example, if you have a directory full of pcaps such as:

iphone7-b-Wed0945-5days.pcap  
win-work-Wed0945-5days.pcap
iphone7-a-Wed0945-5days.pcap
iphone7-c-Wed0945-5days.pcap  
win10homedesktop-Wed0945-5days.pcap

You might create an assignments.json file that looks like:

{
        "win" : "Administrator workstation",
        "win10homedestop" : "Business workstation",
        "iphone7" : "Smartphone"
}

NOTE: the "-" in the filename is mandatory.
-----

**Comment by CStephenson970** [comment]
An example label_assignments.json file can now be found in the data directory. Still need to add the documentation, so I'll leave this open.
