### ISSUE TITLE
Selection of either IP or MAC for training steps

### ISSUE THREAD

**Issue by gregs5** [Lab41/PoseidonML#45]
In the model training step, it would be helpful to have the ability to specify whether the selection from the PCAP was based on a single MAC, or a single IP address, because depending on how the packet capture was acquired, we might want to select on MAC (to survive things like DHCP-based IP address rotation), or on IP address.

**Comment by CStephenson970** [comment]
This feature has now been added.  In the config, "source identifier" can be set to "MAC" to select based on the MAC address, or "IP" to select based on the IP address.

**Comment by lostminty** [comment]
Is this feature still available?

**Comment by cglewis** [comment]
@lostminty looks like the config option is still there: https://github.com/CyberReboot/NetworkML/blob/master/networkml/configs/config.json#L8 but it is no longer an active option that does anything.  MAC address is the identifier it uses at this point, if you'd like to open a PR that uses that config option to use something other than MAC as the identifier, I'd be happy to review/merge.

**Comment by lostminty** [comment]
@cglewis OK, thanks. I'll wait on making a PR. It's regarding integrating https://github.com/wanduow/libprotoident (Layer 7 protocol identifier) into networkml as a source of additional features. I've asked on the libprotoident issue page whether the mac addresses are possible to output, currently it's just IP addresses.
