### ISSUE TITLE
support IPv6 traffic

### ISSUE THREAD

**Issue by cglewis** [Lab41/PoseidonML#78]

**Comment by alshaboti** [comment]
Hi, 
I am happy to contribute on this. 
What I am thinking of is to start from reader.py file [here](https://github.com/Lab41/PoseidonML/blob/775ea5107da021378e238371c3ce74b80267d16f/NodeClassifier/utils/reader.py#L26). 
Things to be changed:
- Handling the source_str and destination_str at [parse_packet_head](https://github.com/Lab41/PoseidonML/blob/775ea5107da021378e238371c3ce74b80267d16f/NodeClassifier/utils/reader.py#L7)  function. 
- No need to change the [parse_packet_data](https://github.com/Lab41/PoseidonML/blob/775ea5107da021378e238371c3ce74b80267d16f/NodeClassifier/utils/reader.py#L57) function. 


Am I right?

**Comment by cglewis** [comment]
@alshaboti that would be great, we'd welcome the contribution!
